### ISSUE TITLE
Adjust Voting Rule

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#11]
I believe we need to create some slack in the voting rule to allow for abstentions or delegation of vote. If a player doesn't want to be constantly involved in voting in the game, they COULD declare a proxy player or declare abstention on their player-space. 

This would allow the game to move forward while allowing less active players to engage with us at their pace.

**Comment by Flaxscrip** [comment]
@macterra also had a possible recommendation from another Nomicon instance. David - would you like to share the concept here?

**Comment by macterra** [comment]
Another Nomicon I am managing has 16 players but only 5 are assigned a "maintainer" role, taking the name from the gitlab role that approve merge requests. The maintainer inherits all the rights and responsibilities of the player role, with the additional right to approve merge requests. Players can still raise issues and submit merge requests.

**Comment by Flaxscrip** [comment]
I like it. Simple. Can we limit commit ability to people assigned the new maintainer role?

**Comment by Flaxscrip** [comment]
@genecyber asked not to be in the Maintainer role. I'll adjust the roster to be @dawnTestCode @Flaxscrip. Reminder that the role of [Maintainer](https://github.com/cryptotechguru/EDENomicon/tree/master/Roles/Maintainer) is to review PRs in a timely manner.
