### ISSUE TITLE
EDEN Protocol Definition

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#12]
I'm creating this issue to begin the definition of our web-of-trust.

**Comment by Flaxscrip** [comment]
I just broke the rules by accidentally committing to Master instead of a PR. My changes define the EDEN Protocol Definition project in commit # [e189bb7a798732164a5131bd5607ae4c68a45796](https://github.com/cryptotechguru/EDENomicon/commit/e189bb7a798732164a5131bd5607ae4c68a45796). 

We COULD roll it back and review it after I properly re-submit it as a PR. **OR** We COULD tally a vote here by existing players to accept the commit to the EDENomicon.

@macterra - do you have any best practice recommendation for us?

**Comment by macterra** [comment]
I recommend reverting the change and submitting a PR. We should configure the repo to protect the master branch.

**Comment by Flaxscrip** [comment]
I reverted the commit and protected the repo to require PR and review. Thank you for the recommendation. I will resubmit the commit with additional changes today.
