### ISSUE TITLE
Gamifying our work with Achievements

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#16]
I'd like to propose the creation of Achievements as rewards for Players that can perform and meet the completion criteria.

**Comment by genecyber** [comment]
I suggest we start simply with test/image achievements, and potentially evolve to using some sort of blockchain NFT assets as achievements

**Comment by Flaxscrip** [comment]
I have a demo achievement but I messed up the link. I'll submit a PR to fix it. 

I agree - these achievements will one day link with crypto assets and rewards! Exciting!

**Comment by Flaxscrip** [comment]
https://nomicon.edenprotocol.io/Achievements/crypto-guru/

**Comment by Flaxscrip** [comment]
We need to come back to this as we develop Project Metatron.
