### ISSUE TITLE
Project rules duplicated

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/EDENomicon#19]
Top page and project subfolder have duplicate rules.

**Comment by Flaxscrip** [comment]
I submitted PR #20 with a possible fix. I'd like to keep a 'summary' (first line) on the top page for ease of use and readability to newcomers. See proposed PR.

**Comment by Flaxscrip** [comment]
Oops, wait... I already merged it. That's what happens when I bundle too much in the same PR. I'll keep it 1-to-1 from now on.
