### ISSUE TITLE
Select a new theme for the site

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/EDENomicon#2]

**Comment by Flaxscrip** [comment]
My preferences: 

1. https://pages-themes.github.io/architect/
1. https://pages-themes.github.io/cayman/
1. https://pages-themes.github.io/minimal/

**Comment by Flaxscrip** [comment]
Multi-Vote 1: https://github.com/cryptotechguru/EDENomicon/wiki/Vote-1

**Comment by macterra** [comment]
Updated site to use the Cayman theme
