### ISSUE TITLE
We need a EDEN Protocol roadmap

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#26]
We need to create a roadmap that will provide a better breakdown of EDEN's _3 steps_ of maturity. We have source content in the marketing slides, but that needs to be discussed and incorporated formally in the EDENomicon. The roadmap will also provide a place to discuss and document future requirements and vision for the protocol.

The 3 maturity steps discussed so far:: 

- Step 1: Data Notarization to provide product traceability across the supply chain.
- Step 2: Data Standardization to provide structures to organize and publish data to the network.
- Step 3: Data Tokenization to provide ethical exchange of information on the network.

I suggest we create a document in the Wiki that will be editable by all for a period of time. The Wiki keeps a revision of each change although it does not require reviews ; this makes it easier to collaborate on wording using the Wiki.

@macterra - Do you have any Nomicon best practices that might be relevant here?

**Comment by angelabacca** [comment]
Are you just needing me to close this?

**Comment by Flaxscrip** [comment]
No, we should keep this issue open until we publish a full roadmap. Here we can discuss the next steps of our roadmap. I've been working on some numbers and work breakdown. I'll start publishing these in the nomicon this week to move these issues forward toward resolutions we can vote on.

**Comment by Flaxscrip** [comment]
I "assigned" you and Dawn assuming the 3 of us would be the most likely players to contribute to the roadmap. Shannon and James will likely focus on more technical tasks. The assignments are not mandatory, they are more for notifications. We should probably define that more clearly in the Nomicon rules themselves. I'll propose a PR later this week with some language to clarify that.

You can also manage your notifications at the top of the screen by clicking on the "Subscribe|Unsubscribe" button.

**Comment by angelabacca** [comment]
Yes, I think that would be helpful. That makes sense.

Angela Bacca
415.515.7483

*LinkedIn <http://www.linkedin.com/pub/angela-bacca/6/308/896/> - Facebook
<https://www.facebook.com/angelabacca?_rdr> - Twitter
<https://twitter.com/angelabacca>*

**Comment by Flaxscrip** [comment]
Closing this issue. We are re-planning the roadmap as part of Project Metatron.
