### ISSUE TITLE
ROLL CALL and Projects Archive

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#34]
As 2020 comes to a close, I'd like to wish everyone a joyful holiday season. May 2021 be a year for growth and re-building.

** This is a Roll Call to all Players **

Thank you for everyone who contributed to the Nomicon in 2019-2020. I need to clean-up the Projects repository; I will migrate the current Projects to an new Archive folder. 

The EDA is about to go in fund raising mode. I will re-map the projects to match the new EDA Roadmap.

Please let me know here or by email if you are interested and available to continue to work on EDEN. Your existing contributions are and will remained recognized through the continued history of the Nomicon. New assignments and roles will need to be defined in 2021. 

Happy holidays!

Christian.

**Comment by angelabacca** [comment]
I am definitely in, happy new year!

**Comment by macterra** [comment]
Happy to help

**Comment by Jxturner10** [comment]
Cool I'm in

**Comment by Flaxscrip** [comment]
Closing Roll Call.
