### ISSUE TITLE
Prepare Metatron Github Repository

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#39]
Prepare the Metatron github repository for the Metatron Launch Project.

**Comment by macterra** [comment]
Some things to check:

- verify the license is consistent with Filecoin projects
- remove any credentials from repo
- remove unused files and folders
- move type assets from test TSR chain to main TESS chain
- ensure python code structure is standard

**Comment by macterra** [comment]
Type assets have been moved to TESS. I'll still have to remove them from test TSR, but that will have to wait until I finish the terminate feature (in test now). I'll also have to start mining TSR again, on hold currently to run the metatron node at http://test.metagamer.org:5000/explorer

**Comment by macterra** [comment]
> verify the license is consistent with Filecoin projects

done

> remove any credentials from repo

done

> remove unused files and folders

done

> move type assets from test TSR chain to main TESS chain

done

> ensure python code structure is standard

pending?

**Comment by aiggdev** [comment]
the python code structure is standard.

**Comment by realChainLife** [comment]
Great update @Flaxscrip! Reviewing the bounty milestones shortly.

**Comment by Flaxscrip** [comment]
Thank you @realChainLife - Excited to have you on here!
