### ISSUE TITLE
Add new players to roster

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/EDENomicon#4]
Add @dawnTestCode and @genecyber to the [player roster](https://github.com/cryptotechguru/EDENomicon/tree/master/Roles/Player)

**Comment by Flaxscrip** [comment]
Added @dawnTestCode to the Roster with comments (see commit notes).

**Comment by Jxturner10** [comment]
@Flaxscrip Hello EDEN

**Comment by Flaxscrip** [comment]
@Jxturner10 - Please create a fork of https://github.com/cryptotechguru/player-space and edit your copy of the player-space as described in https://github.com/cryptotechguru/EDENomicon/tree/master/Roles/Player

Send me the link once your player-space is ready and I'll be able to add you to the roster.

**Comment by Flaxscrip** [comment]
I'd like to suggest that we remove the need for the "Hacker" theme. Everyone should use the theme they prefer.

**Comment by angelabacca** [comment]
Should I come in as "player"?

**Comment by Flaxscrip** [comment]
@angelabacca  - Yes - Welcome!

"player" is the main and simplest role. At some point, you will also likely become a [gatekeeper](https://nomicon.edenprotocol.io/Roles/Gatekeeper/), but that will be later in our project as we define the requirements for our pilot projects.

All you need to do is click the "fork" button at the top of [the generic player-space](https://github.com/cryptotechguru/player-space). Once it is _forked_ in your personal account, you can click the "pen" icon at the top to edit the content with your own profile information.

Ping me here or on Slack and, as one of the Operators, I will add you to the appropriate player [roles](https://nomicon.edenprotocol.io/Roles/).

Welcome to the EDENomicon game!

**Comment by angelabacca** [comment]
I think I did this, but not sure if I did it right. Let me know!

Angela Bacca
415.515.7483

*LinkedIn <http://www.linkedin.com/pub/angela-bacca/6/308/896/> - Facebook
<https://www.facebook.com/angelabacca?_rdr> - Twitter
<https://twitter.com/angelabacca>*

**Comment by Flaxscrip** [comment]
@Jxturner10 - Let me know if you need any help setting up your player-roster. We have a getting started document in the wiki: https://github.com/cryptotechguru/EDENomicon/wiki/Getting-Started

**Comment by Flaxscrip** [comment]
The Player Roster remains open to new and returning players! We will be managing the development and pilot communities as part of Project Metatron.
