### ISSUE TITLE
Define Pilot Kick-off Next Steps

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#6]
We need to define the next steps necessary to support the upcoming EDA pilots in Summer of 2020.

**Comment by Flaxscrip** [comment]
Proposed next steps for Pilot kick-off:

- Create a PullRequest that adds Project functionality to EDENomicon (PR #8).
- Create a Pilot project and charter in EDENomicon. 
- Create a questionnaire to determine list of Pilot candidates (ex: name, product, role, etc).
- Create pilot program defining supply chain benefits to pilot participants (ex: traceability).
- Define pilot(s) scope and workflows.
- Deploy minimal technologies necessary to enable pilot workflows.
- Document pilot decisions, objectives, methods, and results along the way.
- Execute, execute, execute. 
- Presentation of results and next steps at conferences in Fall of 2020.

**Comment by genecyber** [comment]
👍
