### ISSUE TITLE
Adopt the "Projects" governance structure from Cryptonomicon

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#7]
I would like to put a vote for the adoption of the Projects governance structure as described by the Cryptonomicon: https://github.com/cryptotechguru/Cryptonomicon#projects

We now have a need for multiple parallel streams of work (ex: website, pilots, protocol, etc). Each of these can be contained in its own Project to facilitate voting and governance. 

Please review the rules of the Project. I will be proposing a Pull Request to change the EDENomicon. I will require your review and vote *before* we agree to merge the change. Also feel free to discuss here any amendments, changes, etc we may want to do to the Projects definition.

**Comment by genecyber** [comment]
this idea of using "Projects" works for me.
